# Pitch Predict

## Data Acquisition

In [146]:
import pybaseballstats as pyb
import polars as pl

For this test we will only be looking at Max Scherzer's data so find his player id and use that to filter the data. 


In [147]:
# pyb.retrosheet.player_lookup(first_name="Max", last_name="Scherzer")

Get all available pitch by pitch data

In [149]:
# df = df.filter(pl.col("pitcher") == 453286)

In [150]:
# print(df.columns)

In [151]:
# df.sink_parquet("scherzer.parquet")

In [217]:
df = pl.read_parquet("scherzer.parquet")

In [218]:
feature_cols = [
    "pitch_type",
    "game_date",
    "release_speed",
    "release_pos_x",
    "release_pos_z",
    "zone",
    "stand",
    "p_throws",
    "balls",
    "strikes",
    "pfx_x",
    "pfx_z",
    "plate_x",
    "plate_z",
    "on_3b",
    "on_2b",
    "on_1b",
    "outs_when_up",
    "inning",
    "inning_topbot",
    "hc_x",
    "hc_y",
    "vx0",
    "vy0",
    "vz0",
    "ax",
    "ay",
    "az",
    "sz_top",
    "sz_bot",
    "effective_speed",
    "release_spin_rate",
    "release_extension",
    "release_pos_y",
    "at_bat_number",
    "pitch_number",
    "bat_score",
    "fld_score",
    "if_fielding_alignment",
    "of_fielding_alignment",
    "spin_axis",
    "n_thruorder_pitcher",
    "n_priorpa_thisgame_player_at_bat",
    "pitcher_days_since_prev_game",
    "api_break_z_with_gravity",
    "api_break_x_arm",
    "api_break_x_batter_in",
]

In [219]:
df = df.select(feature_cols)

In [220]:
df.shape

(31531, 47)

In [221]:
df.describe()

shape: (9, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ pitch_typ ┆ game_date ┆ release_s ┆ … ┆ pitcher_d ┆ api_break ┆ api_break ┆ api_brea │
│ ---       ┆ e         ┆ ---       ┆ peed      ┆   ┆ ays_since ┆ _z_with_g ┆ _x_arm    ┆ k_x_batt │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ _prev_gam ┆ ravity    ┆ ---       ┆ er_in    │
│           ┆ str       ┆           ┆ f64       ┆   ┆ e         ┆ ---       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆           ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 31190     ┆ 31531     ┆ 31181.0   ┆ … ┆ 29682     ┆ 31176.0   ┆ 31176.0   ┆ 31176.0  │
│ null_coun ┆ 341       ┆ 0         ┆ 350.0     ┆ … ┆ 1849      ┆ 355.0     ┆ 355.0     ┆ 355.0    │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 89.318101 ┆ … ┆ null      ┆ 2.237408  ┆ 0.52092   ┆ -0.12285 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ std       ┆ null      ┆ null      ┆ 5.875498  ┆ … ┆ null      ┆ 1.044563  ┆ 0.757316  ┆ 0.910933 │
│ min       ┆ CH        ┆ 2014-03-1 ┆ 37.9      ┆ … ┆ 10        ┆ 0.02      ┆ -2.12     ┆ -2.42    │
│           ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 85.0      ┆ … ┆ null      ┆ 1.34      ┆ -0.17     ┆ -0.96    │
│ 50%       ┆ null      ┆ null      ┆ 91.2      ┆ … ┆ null      ┆ 1.83      ┆ 0.83      ┆ -0.26    │
│ 75%       ┆ null      ┆ null      ┆ 94.4      ┆ … ┆ null      ┆ 2.98      ┆ 1.1       ┆ 0.81     │
│ max       ┆ SL        ┆ 2025-03-2 ┆ 99.4      ┆ … ┆ 9         ┆ 7.8       ┆ 2.81      ┆ 2.81     │
│           ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [222]:
df = df.drop_nulls("pitch_type")

In [223]:
df = df.sort(["game_date", "at_bat_number", "pitch_number"])

In [ ]:
keep_pitch_types = (
    df.select(pl.col("pitch_type").value_counts(normalize=True))
    .unnest("pitch_type")
    .filter(pl.col("proportion") > 0.01)
    .select(pl.col("pitch_type").unique())
    .to_series()
    .to_list()
)
df = df.with_columns(
    pl.when(pl.col("pitch_type").is_in(keep_pitch_types))
    .then(pl.col("pitch_type"))
    .otherwise(pl.lit("other"))
    .alias("pitch_type"),
)

In [226]:
df = df.with_columns(
    pl.col("pitch_type").shift(-1).alias("next_pitch_type (target)"),
)

In [227]:
df = df.drop_nulls(["pitch_type", "next_pitch_type (target)"])

In [228]:
df.select(pl.col(["pitch_type", "next_pitch_type (target)"])).head(10)

shape: (10, 2)
┌────────────┬──────────────────────────┐
│ pitch_type ┆ next_pitch_type (target) │
│ ---        ┆ ---                      │
│ str        ┆ str                      │
╞════════════╪══════════════════════════╡
│ FF         ┆ FF                       │
│ FF         ┆ FF                       │
│ FF         ┆ FF                       │
│ FF         ┆ FF                       │
│ FF         ┆ SL                       │
│ SL         ┆ FF                       │
│ FF         ┆ FF                       │
│ FF         ┆ FF                       │
│ FF         ┆ CH                       │
│ CH         ┆ FF                       │
└────────────┴──────────────────────────┘

## featurization

In [229]:
df.describe()

shape: (9, 49)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ pitch_typ ┆ game_date ┆ release_s ┆ … ┆ api_break ┆ api_break ┆ api_break ┆ next_pit │
│ ---       ┆ e         ┆ ---       ┆ peed      ┆   ┆ _z_with_g ┆ _x_arm    ┆ _x_batter ┆ ch_type  │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ravity    ┆ ---       ┆ _in       ┆ (target) │
│           ┆ str       ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 31189     ┆ 31189     ┆ 31171.0   ┆ … ┆ 31171.0   ┆ 31171.0   ┆ 31171.0   ┆ 31189    │
│ null_coun ┆ 0         ┆ 0         ┆ 18.0      ┆ … ┆ 18.0      ┆ 18.0      ┆ 18.0      ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 89.329813 ┆ … ┆ 2.236901  ┆ 0.520915  ┆ -0.122838 ┆ null     │
│ std       ┆ null      ┆ null      ┆ 5.831489  ┆ … ┆ 1.043475  ┆ 0.757298  ┆ 0.910918  ┆ null     │
│ min       ┆ CH        ┆ 2014-04-0 ┆ 71.1      ┆ … ┆ 0.02      ┆ -2.12     ┆ -2.42     ┆ CH       │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 85.0      ┆ … ┆ 1.34      ┆ -0.17     ┆ -0.96     ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ 91.2      ┆ … ┆ 1.83      ┆ 0.83      ┆ -0.26     ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ 94.4      ┆ … ┆ 2.98      ┆ 1.1       ┆ 0.81      ┆ null     │
│ max       ┆ other     ┆ 2025-03-2 ┆ 99.4      ┆ … ┆ 5.83      ┆ 2.81      ┆ 2.81      ┆ other    │
│           ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [230]:
df = df.with_columns(
    pl.col("stand").cast(pl.Categorical).to_physical().alias("stand"),
    pl.col("p_throws").cast(pl.Categorical).to_physical().alias("p_throws"),
    pl.col("inning_topbot").cast(pl.Categorical).to_physical().alias("inning_topbot"),
    pl.col("effective_speed").cast(pl.Float32).alias("effective_speed"),
    pl.col("release_spin_rate").cast(pl.Float32).alias("release_spin_rate"),
    pl.col("release_extension").cast(pl.Float32).alias("release_extension"),
    pl.col("if_fielding_alignment")
    .cast(pl.Categorical)
    .to_physical()
    .alias("if_fielding_alignment"),
    pl.col("of_fielding_alignment")
    .cast(pl.Categorical)
    .to_physical()
    .alias("of_fielding_alignment"),
    pl.col("spin_axis").cast(pl.Float32).alias("spin_axis"),
    pl.col("pitcher_days_since_prev_game")
    .cast(pl.Float32)
    .alias("pitcher_days_since_prev_game"),
)
df = df.with_columns(
    pl.col("pitch_type").cast(pl.Categorical).to_physical().alias("pitch_type"),
)

In [231]:
df = df.fill_null(-1)

In [232]:
df.describe()

shape: (9, 49)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ pitch_typ ┆ game_date ┆ release_s ┆ … ┆ api_break ┆ api_break ┆ api_break ┆ next_pit │
│ ---       ┆ e         ┆ ---       ┆ peed      ┆   ┆ _z_with_g ┆ _x_arm    ┆ _x_batter ┆ ch_type  │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ravity    ┆ ---       ┆ _in       ┆ (target) │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 31189.0   ┆ 31189     ┆ 31189.0   ┆ … ┆ 31189.0   ┆ 31189.0   ┆ 31189.0   ┆ 31189    │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.091795  ┆ null      ┆ 89.277681 ┆ … ┆ 2.235033  ┆ 0.520038  ┆ -0.123344 ┆ null     │
│ std       ┆ 1.430469  ┆ null      ┆ 6.220379  ┆ … ┆ 1.046066  ┆ 0.75796   ┆ 0.910899  ┆ null     │
│ min       ┆ 0.0       ┆ 2014-04-0 ┆ -1.0      ┆ … ┆ -1.0      ┆ -2.12     ┆ -2.42     ┆ CH       │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 0.0       ┆ null      ┆ 85.0      ┆ … ┆ 1.34      ┆ -0.17     ┆ -0.96     ┆ null     │
│ 50%       ┆ 0.0       ┆ null      ┆ 91.2      ┆ … ┆ 1.83      ┆ 0.83      ┆ -0.26     ┆ null     │
│ 75%       ┆ 2.0       ┆ null      ┆ 94.4      ┆ … ┆ 2.98      ┆ 1.1       ┆ 0.81      ┆ null     │
│ max       ┆ 5.0       ┆ 2025-03-2 ┆ 99.4      ┆ … ┆ 5.83      ┆ 2.81      ┆ 2.81      ┆ other    │
│           ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## creating sequences

In [233]:
import numpy as np

In [234]:
SEQ_LEN = 10
feature_cols.remove("game_date")
features = df[feature_cols].to_numpy()
labels = df["next_pitch_type (target)"].to_numpy()

In [235]:
X, y = [], []
for i in range(SEQ_LEN, len(df)):
    X.append(features[i - SEQ_LEN : i])
    y.append(labels[i])
X = np.array(X)
y = np.array(y)

In [236]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
class_names = list(le.classes_)
print(class_names)

[np.str_('CH'), np.str_('CU'), np.str_('FC'), np.str_('FF'), np.str_('SL'), np.str_('other')]


## model

In [238]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

# --- 1) Split your data (no shuffle) ---
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, shuffle=False)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, shuffle=False
)

# --- 2) One‐hot encode your labels ---
num_classes = len(np.unique(y_train))
y_train_oh = tf.keras.utils.to_categorical(y_train, num_classes)
y_val_oh = tf.keras.utils.to_categorical(y_val, num_classes)
y_test_oh = tf.keras.utils.to_categorical(y_test, num_classes)

# --- 3) Compute class‐weights ---
#    so that minority classes get proportionally larger loss weights
integer_train_labels = np.argmax(y_train_oh, axis=1)
class_weights_array = compute_class_weight(
    class_weight="balanced", classes=np.arange(num_classes), y=integer_train_labels
)
class_weight_dict = dict(enumerate(class_weights_array))

# --- 4) Build tf.data pipelines (optional but efficient) ---
batch_size = 32
train_ds = (
    tf.data.Dataset.from_tensor_slices((X_train, y_train_oh))
    .shuffle(5000)
    .batch(batch_size)
    .prefetch(tf.data.AUTOTUNE)
)
val_ds = (
    tf.data.Dataset.from_tensor_slices((X_val, y_val_oh))
    .batch(batch_size)
    .prefetch(tf.data.AUTOTUNE)
)
test_ds = (
    tf.data.Dataset.from_tensor_slices((X_test, y_test_oh))
    .batch(batch_size)
    .prefetch(tf.data.AUTOTUNE)
)

# --- 5) Revised Model: Bidirectional, Stacked LSTM ---
seq_len, num_feats = X_train.shape[1], X_train.shape[2]

model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(seq_len, num_feats)),
        tf.keras.layers.LSTM(16),
        tf.keras.layers.Dense(num_classes, activation="softmax"),
    ]
)

# --- 6) Compile with gradient clipping ---
opt = tf.keras.optimizers.Adam(learning_rate=1e-4, clipnorm=1.0)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])

# model.summary()

# --- 7) Train with early stopping and class‐weights ---
es = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=5, restore_best_weights=True
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=30,
    class_weight=class_weight_dict,
    callbacks=[es],
)

# --- 8) Final evaluation on test data ---
test_loss, test_acc = model.evaluate(test_ds, verbose=1)
print(f"Test  Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")


Epoch 1/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1174 - loss: 1.6722 - val_accuracy: 0.0466 - val_loss: 1.8685
Epoch 2/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1184 - loss: 1.6472 - val_accuracy: 0.0453 - val_loss: 1.8443
Epoch 3/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1256 - loss: 1.6163 - val_accuracy: 0.0984 - val_loss: 1.8091
Epoch 4/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1633 - loss: 1.6267 - val_accuracy: 0.0992 - val_loss: 1.8054
Epoch 5/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2405 - loss: 1.6304 - val_accuracy: 0.2232 - val_loss: 1.7608
Epoch 6/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2637 - loss: 1.6143 - val_accuracy: 0.2230 - val_loss: 1.7682
Epoch 7/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2695 - loss: 1.6344 - val_accuracy: 0.2219 - val_loss: 1.7723
Epoch 8/30
683/683 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2649 - loss: 1.5895 - val_accuracy: 0.

In [239]:
import numpy as np
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
)


# 1) Gather true labels and preds from a tf.data.Dataset
def dataset_to_arrays(ds):
    """Extract (X_batch, y_batch) from a batched tf.data.Dataset of (X, one-hot y)."""
    ys_true = []
    ys_pred = []
    for Xb, yb in ds:
        # model.predict returns (batch, num_classes) probs
        probs = model.predict(Xb, verbose=0)
        ys_true.append(np.argmax(yb.numpy(), axis=1))
        ys_pred.append(np.argmax(probs, axis=1))
    return (
        np.concatenate(ys_true),
        np.concatenate(ys_pred),
        np.concatenate([model.predict(Xb, verbose=0) for Xb, _ in ds]),
    )


# Validation
y_val_true, y_val_pred, y_val_probs = dataset_to_arrays(val_ds)

from sklearn.metrics import classification_report, confusion_matrix

# Suppose your classes are 0,1,2,3,4  (i.e. le.classes_.shape == 5)
labels = list(range(len(class_names)))  # [0,1,2,3,4]

print("=== Validation Classification Report ===")
print(
    classification_report(
        y_val_true, y_val_pred, labels=labels, target_names=class_names
    )
)

cm = confusion_matrix(y_val_true, y_val_pred, labels=labels)
print("Confusion matrix:\n", cm)


# Top-2 accuracy
top2_preds = np.argsort(y_val_probs, axis=1)[:, -2:]
top2_acc = np.mean([y_val_true[i] in top2_preds[i] for i in range(len(y_val_true))])
print(f"Top-2 Accuracy: {top2_acc:.4f}")

# 2) Repeat on Test set
y_test_true, y_test_pred, y_test_probs = dataset_to_arrays(test_ds)

print("\n=== Test Classification Report ===")
print(
    classification_report(
        y_test_true, y_test_pred, labels=labels, target_names=class_names
    )
)
print("Test Accuracy:", accuracy_score(y_test_true, y_test_pred))

cm_test = confusion_matrix(y_test_true, y_test_pred)
print("Test Confusion matrix:\n", cm_test)

top2_test = np.argsort(y_test_probs, axis=1)[:, -2:]
top2_test_acc = np.mean(
    [y_test_true[i] in top2_test[i] for i in range(len(y_test_true))]
)
print(f"Test Top-2 Accuracy: {top2_test_acc:.4f}")


=== Validation Classification Report ===
              precision    recall  f1-score   support

          CH       0.14      0.12      0.13       676
          CU       0.13      0.05      0.07       447
          FC       0.10      0.52      0.17       460
          FF       0.47      0.31      0.37      2154
          SL       0.22      0.05      0.08       940
       other       0.00      0.00      0.00         0

    accuracy                           0.22      4677
   macro avg       0.18      0.17      0.14      4677
weighted avg       0.30      0.22      0.23      4677

Confusion matrix:
 [[  81   24  307  225   33    6]
 [  40   23  240  120   24    0]
 [  51   16  238  136   17    2]
 [ 272   85 1036  658   79   24]
 [ 122   35  451  275   44   13]
 [   0    0    0    0    0    0]]
Top-2 Accuracy: 0.3729


/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo


=== Test Classification Report ===
              precision    recall  f1-score   support

          CH       0.12      0.10      0.11       622
          CU       0.09      0.03      0.04       561
          FC       0.10      0.52      0.16       441
          FF       0.46      0.28      0.35      2142
          SL       0.18      0.06      0.09       911
       other       0.00      0.00      0.00         0

    accuracy                           0.20      4677
   macro avg       0.16      0.16      0.12      4677
weighted avg       0.28      0.20      0.21      4677

Test Accuracy: 0.20440453282018387
Test Confusion matrix:
 [[  60   19  309  189   36    9]
 [  59   16  281  153   43    9]
 [  40   21  228  118   26    8]
 [ 238   87 1060  601  123   33]
 [  88   42  459  249   51   22]
 [   0    0    0    0    0    0]]
Test Top-2 Accuracy: 0.3592


/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/nicocarbone/Documents/dev/PitchPredict/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo